from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from tests.carry_v2_git import require_git_worktree
from btcquant.research.carry_v2_financing import (
    FinancingInputError,
    FinancingPolicy,
    balance_sheet_identity,
    borrow_sensitivity,
    entry_edge,
    funding_distribution,
    funding_fraction_above,
    structure_scenarios,
    recursive_financing_ceiling,
)


def test_structures_preserve_equal_btc_quantity_and_balance_identity() -> None:
    policy = FinancingPolicy()
    structures = structure_scenarios(policy, reference_price=80_000.0)

    for structure in structures.values():
        assert structure.spot_qty == pytest.approx(structure.perp_qty)
        assert structure.quantity_delta == pytest.approx(0.0)
        balance = structure.balance_sheet()
        assert balance["identity_residual"] == pytest.approx(0.0)
        assert balance["net_equity"] == pytest.approx(policy.equity)


def test_current_three_x_break_even_is_two_thirds_of_borrow_rate() -> None:
    structure = structure_scenarios(FinancingPolicy(), reference_price=80_000.0)["A_CURRENT_V1_3X"]
    assert structure.recurring_break_even == pytest.approx(2.0 / 3.0 * 0.10)
    assert structure.borrow_principal == pytest.approx(8000.0)
    assert structure.gross_exposure == pytest.approx(24_000.0)


def test_unlevered_has_zero_borrow_drag_and_no_historical_cap_scenario() -> None:
    structures = structure_scenarios(FinancingPolicy(), reference_price=80_000.0)
    unlevered = structures["B_THEORETICAL_CASH_FUNDED_SPOT"]
    assert unlevered.borrow_principal == pytest.approx(0.0)
    assert unlevered.recurring_break_even == pytest.approx(0.0)
    assert "C_DOCUMENTED_CAP_SCENARIO" not in structures


def test_fully_loaded_break_even_includes_round_trip_costs_and_target_return() -> None:
    policy = FinancingPolicy()
    structure = structure_scenarios(policy, reference_price=80_000.0)["A_CURRENT_V1_3X"]
    assert structure.round_trip_cost(policy) == pytest.approx(48.0)
    target_zero = structure.fully_loaded_break_even(policy, 90, return_capital_base=policy.equity)
    target_three = structure.fully_loaded_break_even(
        policy, 90, target_return_on_equity=0.03, return_capital_base=policy.equity
    )
    assert target_three > target_zero > structure.recurring_break_even


def test_funding_distribution_is_hourly_rate_annualized() -> None:
    distribution = funding_distribution((0.01 / (365.25 * 24.0), 0.02 / (365.25 * 24.0)))
    assert distribution["count"] == 2
    assert distribution["median"] == pytest.approx(0.015)
    assert distribution["p75"] == pytest.approx(0.0175)
    assert funding_fraction_above((0.01, 0.02, 0.03), 0.02) == pytest.approx(1 / 3)


def test_entry_edge_uses_same_entry_event_without_search() -> None:
    policy = FinancingPolicy()
    structure = structure_scenarios(policy, reference_price=80_000.0)["A_CURRENT_V1_3X"]
    edge = entry_edge(
        structure,
        smooth_funding_ann=0.03,
        policy=policy,
        holding_days=90,
        return_capital_base=policy.equity,
    )
    assert edge["funding_income_on_equity"] == pytest.approx(0.09)
    assert edge["borrow_drag_on_equity"] == pytest.approx(0.20)
    assert edge["recurring_net_on_equity"] == pytest.approx(-0.11)
    assert edge["cost_loaded_net_on_equity"] < edge["recurring_net_on_equity"]


def test_balance_sheet_identity_rejects_non_finite_values() -> None:
    with pytest.raises(FinancingInputError):
        balance_sheet_identity(gross_assets=float("inf"), gross_liabilities=1.0, equity=1.0)


def test_artifact_provenance_and_governance_are_fail_closed() -> None:
    artifact_path = Path("audit/carry_v2_financing_feasibility.json")
    if not artifact_path.exists():
        pytest.skip("artifact is generated by commit B")
    root = Path(__file__).resolve().parents[1]
    require_git_worktree(root)
    artifact_name = "audit/carry_v2_financing_feasibility.json"
    artifact = json.loads(artifact_path.read_text(encoding="utf-8"))
    source_sha = artifact["qualification_source_sha"]
    assert len(source_sha) == 40
    source_available = (
        subprocess.run(
            ["git", "-C", str(root), "cat-file", "-e", f"{source_sha}^{{commit}}"],
            check=False,
        ).returncode
        == 0
    )
    if not source_available:
        shallow = subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "--is-shallow-repository"], text=True
        ).strip()
        if shallow == "true":
            pytest.skip("source commit unavailable in shallow CI checkout")
        raise AssertionError("qualification source SHA is not available in full clone")
    assert (
        subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", f"{source_sha}^{{commit}}"], text=True
        ).strip()
        == source_sha
    )
    assert (
        artifact["qualification_source_tree"]
        == subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", f"{source_sha}^{{tree}}"], text=True
        ).strip()
    )
    artifact_commit = subprocess.check_output(
        ["git", "-C", str(root), "log", "--all", "--format=%H", "-1", "--", artifact_name],
        text=True,
    ).strip()
    assert artifact_commit != source_sha
    assert (
        subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", f"{artifact_commit}^"], text=True
        ).strip()
        == source_sha
    )
    assert subprocess.check_output(
        ["git", "-C", str(root), "diff", "--name-only", f"{artifact_commit}^", artifact_commit],
        text=True,
    ).splitlines() == ["audit/carry_v2_financing_feasibility.json"]
    assert artifact["financing"]["liquidation"]["qualification"] is False
    assert artifact["account_specific"]["portfolio_margin_eligibility"] == "UNKNOWN"
    assert artifact["governance"] == {
        "adopted": False,
        "candidate_search": {"performed": False},
        "governed_selection_permitted": False,
        "policy_changed": False,
        "threshold_search": {"performed": False},
    }


def test_current_three_x_is_not_blocked_by_historical_cap() -> None:
    structure = structure_scenarios(
        FinancingPolicy(), reference_price=80_000.0, documented_borrow_cap=50_000_000.0
    )["A_CURRENT_V1_3X"]
    assert structure.borrow_principal == pytest.approx(8000.0)
    assert structure.documented_borrow_cap == pytest.approx(50_000_000.0)
    assert structure.as_dict(FinancingPolicy())["documented_cap_exceeded"] is False
    assert structure.feasibility == "CURRENT_3X_CAPITAL_MECHANICS_NOT_QUALIFIED"


def test_recursive_ceiling_is_explicitly_diagnostic() -> None:
    capacity = recursive_financing_ceiling(4000.0, 0.5)
    assert capacity["max_theoretical_spot_value"] == pytest.approx(8000.0)
    assert capacity["max_theoretical_borrow"] == pytest.approx(4000.0)


def test_unknown_perp_collateral_does_not_double_count_allocated_equity() -> None:
    structures = structure_scenarios(FinancingPolicy(), reference_price=80_000.0)
    for name in ("B_THEORETICAL_CASH_FUNDED_SPOT",):
        structure = structures[name]
        assert structure.allocated_equity == pytest.approx(4000.0)
        assert structure.spot_cash_required == pytest.approx(structure.spot_notional)
        assert structure.perp_initial_margin_required == "UNKNOWN"
        assert structure.additional_collateral_required == "UNKNOWN"
        assert structure.total_capital_required == "UNKNOWN"
        assert structure.capital_denominator_qualified is False
        assert (
            structure.as_dict(FinancingPolicy())["fully_loaded_break_even_status"]
            == "N/A_CAPITAL_DENOMINATOR_UNKNOWN"
        )


def test_return_metrics_are_na_without_qualified_capital_base() -> None:
    policy = FinancingPolicy()
    structure = structure_scenarios(policy, reference_price=80_000.0)[
        "B_THEORETICAL_CASH_FUNDED_SPOT"
    ]
    edge = entry_edge(structure, smooth_funding_ann=0.03, policy=policy, holding_days=90)
    assert edge["annual_funding_income"] == pytest.approx(120.0)
    assert edge["annual_borrow_cost"] == pytest.approx(0.0)
    assert edge["funding_income_on_equity"] == "N/A"
    assert edge["borrow_drag_on_equity"] == "N/A"
    assert edge["recurring_net_on_equity"] == "N/A"
    assert edge["cost_loaded_net_on_equity"] == "N/A"


def test_structure_borrow_rate_is_authoritative_over_policy_default() -> None:
    policy = FinancingPolicy(borrow_rate_ann=0.10)
    structure = structure_scenarios(policy, reference_price=80_000.0)["A_CURRENT_V1_3X"]
    custom = type(structure)(**{**structure.__dict__, "borrow_rate_ann": 0.20})
    assert custom.annual_borrow_cost(policy) == pytest.approx(1600.0)
    assert custom.recurring_break_even == pytest.approx(8000.0 * 0.20 / 12000.0)
    edge = entry_edge(custom, smooth_funding_ann=0.10, policy=policy, return_capital_base=4000.0)
    assert edge["annual_borrow_cost"] == pytest.approx(1600.0)
    assert edge["borrow_drag_on_equity"] == pytest.approx(0.40)


def test_borrow_sensitivity_is_fixed_and_structure_b_has_none() -> None:
    policy = FinancingPolicy()
    structures = structure_scenarios(policy, reference_price=80_000.0)
    sensitivity = borrow_sensitivity(structures["A_CURRENT_V1_3X"], policy)
    assert sensitivity["status"] == "FIXED_BORROW_SENSITIVITY"
    assert [row["borrow_rate_ann"] for row in sensitivity["scenarios"]] == [0.05, 0.10, 0.15, 0.20]
    assert all(
        row["fully_loaded_break_even_target_0pct"] == "N/A" for row in sensitivity["scenarios"]
    )
    assert (
        borrow_sensitivity(structures["B_THEORETICAL_CASH_FUNDED_SPOT"], policy)["status"]
        == "N/A_NO_BORROW"
    )


def test_funding_above_break_even_is_descriptive_only() -> None:
    distribution = funding_distribution((0.01 / (365.25 * 24.0),))
    assert distribution["statistic_classification"] == "DESCRIPTIVE_HOURLY_FUNDING_STATISTIC"


def test_current_cap_is_optional_and_never_defaults_to_pre_alpha() -> None:
    structure = structure_scenarios(FinancingPolicy(), reference_price=80_000.0)["A_CURRENT_V1_3X"]
    assert structure.documented_borrow_cap is None
    assert structure.feasibility == "CURRENT_3X_CAPITAL_MECHANICS_NOT_QUALIFIED"
