from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest


ARTIFACT = Path("audit/carry_v2_pm_exact_mechanics.json")


def _git(*args: str) -> str:
    return subprocess.check_output(["git", *args], text=True).strip()


def test_pm_artifact_has_reproducible_two_commit_provenance() -> None:
    if not ARTIFACT.exists():
        pytest.skip("artifact is generated by the artifact-only commit")
    artifact = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    source_sha = artifact["qualification_source_sha"]
    assert len(source_sha) == 40
    try:
        resolved_source = _git("rev-parse", f"{source_sha}^{{commit}}")
    except subprocess.CalledProcessError:
        if _git("rev-parse", "--is-shallow-repository") == "true":
            pytest.skip("source commit is unavailable in the shallow CI checkout")
        raise
    assert resolved_source == source_sha
    assert artifact["qualification_source_tree"] == _git("rev-parse", f"{source_sha}^{{tree}}")
    assert "artifact_commit_sha" not in artifact
    for path, expected_blob in artifact["qualification_source_files"].items():
        assert _git("rev-parse", f"{source_sha}:{path}") == expected_blob

    artifact_commit = _git("log", "--all", "--format=%H", "-1", "--", str(ARTIFACT))
    assert artifact_commit != source_sha
    assert _git("rev-parse", f"{artifact_commit}^") == source_sha
    assert _git("diff", "--name-only", f"{artifact_commit}^", artifact_commit).splitlines() == [
        str(ARTIFACT)
    ]
    assert artifact["ubtc_mapping"]["ubtc_at_142_mapping"] == "PROVEN"
    assert (
        artifact["decision"]["self_contained_current_v1_3x"]
        == "CURRENT_V1_3X_SELF_CONTAINED_INFEASIBLE_LTV_AND_MARGIN"
    )
    assert artifact["governance"]["adopted"] is False
